### PR TITLE
required, pre-filled phone number because we forgot

### PR DESCRIPTION
**Pull request by adamdruppe**
Robert and Dennis found some missing phone numbers on SF, this is why. The phone was on the user record, but not the application and it got overwritten. I fixed existing records with a script, and this will fix the others going forward.

### CODE REVIEW

**Comment by hcli-work** [comment]
This looks like a pure UI change? Should we also include a validation in the model as well and a spec to go with it?

**Comment by adamdruppe** [comment]
yes, it is pure ui. a validation might make sense since it is decided now this is meant to be a legit required field.

**Comment by hcli-work** [comment]
Agree. How about adding a non-NULL database constraint and then slapping on a validation checking the format? A pure database constraint would be ideal, but I don't yet know how validate a phone number string with just a db constraint.

**Comment by adamdruppe** [comment]
phone number is checked in postgres by `CONSTRAINT CHECK (phone ~* '^[0-9\- ]')` or something like that (pick a better regex at your leisure)

idk how to express it in rails tho

**Comment by hcli-work** [comment]
Great. My vote is for a database constraint rather than a validation then since it provides stronger guarantees.

**Comment by adamdruppe** [comment]
there we go, it is added and the commit is broken up too

**Pull request merged**
